### ISSUE TITLE
rflow package

### ISSUE THREAD

**Issue by terrytangyuan** [xsankar/deepLearnR#1]
Hey, do you want to checkout [rflow package](https://github.com/terrytangyuan/rflow) and help me maintain/develop that? Right now rflow just prints out a python script and then execute it from Python. A fun idea and experiment for me at least :-) Not as flexible but it does the job. It's on-hold now since skflow has been changing quite a lot recently and I don't have much time to maintain rflow. Check out some demos here: https://github.com/terrytangyuan/rflow/tree/master/demo

**Comment by xsankar** [comment]
Thanks Terry. Let us talk after our class work is complete.
